export interface Language {
	language: string;
	latin: boolean;
}

export const languages = [
	{ language: 'Arabic', latin: false },
	{ language: 'Azerbaijani', latin: true },
	{ language: 'Bengali', latin: false },
	{ language: 'Burmese', latin: false },
	{ language: 'Cebuano', latin: true },
	{ language: 'Chinese', latin: false },
	{ language: 'Dutch', latin: true },
	{ language: 'English', latin: true },
	{ language: 'Fula', latin: true },
	{ language: 'French', latin: true },
	{ language: 'German', latin: true },
	{ language: 'Gujarati', latin: false },
	{ language: 'Hakka Chinese', latin: false },
	{ language: 'Hausa', latin: true },
	{ language: 'Hindi', latin: false },
	{ language: 'Igbo', latin: true },
	{ language: 'Indonesian', latin: true },
	{ language: 'Italian', latin: true },
	{ language: 'Japanese', latin: false },
	{ language: 'Javanese', latin: true },
	{ language: 'Jin Chinese', latin: false },
	{ language: 'Kannada', latin: false },
	{ language: 'Korean', latin: false },
	{ language: 'Kurdish', latin: true },
	{ language: 'Madurese', latin: true },
	{ language: 'Magahi', latin: false },
	{ language: 'Maithili', latin: false },
	{ language: 'Malagasy', latin: true },
	{ language: 'Malay', latin: true },
	{ language: 'Malayalam', latin: false },
	{ language: 'Marathi', latin: false },
	{ language: 'Northern Min Chinese', latin: false },
	{ language: 'Odia (Oriya)', latin: false },
	{ language: 'Oromo', latin: true },
	{ language: 'Pashto', latin: false },
	{ language: 'Persian (Farsi)', latin: false },
	{ language: 'Polish', latin: true },
	{ language: 'Portuguese', latin: true },
	{ language: 'Punjabi', latin: false },
	{ language: 'Romanian', latin: true },
	{ language: 'Russian', latin: false },
	{ language: 'Saraiki', latin: false },
	{ language: 'Shona', latin: true },
	{ language: 'Sindhi', latin: false },
	{ language: 'Somali', latin: true },
	{ language: 'Southern Min Chinese', latin: false },
	{ language: 'Spanish', latin: true },
	{ language: 'Sundanese', latin: true },
	{ language: 'Swahili (Kiswahili)', latin: true },
	{ language: 'Swedish', latin: true },
	{ language: 'Tagalog (Filipino)', latin: true },
	{ language: 'Tamil', latin: false },
	{ language: 'Telugu', latin: false },
	{ language: 'Thai', latin: false },
	{ language: 'Turkish', latin: true },
	{ language: 'Ukrainian', latin: false },
	{ language: 'Urdu', latin: false },
	{ language: 'Uyghur', latin: false },
	{ language: 'Uzbek', latin: true },
	{ language: 'Vietnamese', latin: true },
	{ language: 'Wu Chinese', latin: false },
	{ language: 'Xiang Chinese', latin: false },
	{ language: 'Yoruba', latin: true },
	{ language: 'Yue Chinese (Cantonese)', latin: false },
	{ language: 'Zhuang', latin: true },
	{ language: 'Zulu', latin: true }
];
